USE [AcademySMGroups]
GO

INSERT INTO [dbo].[Categories]
           ([Name]
           ,[MainCategory]
           ,[Icon])
     VALUES
           ('Desenvolvimento Web', 'Tecnologia da Informação e Ciência da Computação','bi bi-code'),
		   ('Desenvolvimento Mobile', 'Tecnologia da Informação e Ciência da Computação','bi bi-code'),
		   ('Algoritmos', 'Tecnologia da Informação e Ciência da Computação','bi bi-code'),
		   ('Desenvolvimento de Software', 'Tecnologia da Informação e Ciência da Computação','bi bi-code'),
		   ('Bancos de Dados', 'Tecnologia da Informação e Ciência da Computação','bi bi-database-fill'),
		   ('Ciência de Dados', 'Tecnologia da Informação e Ciência da Computação','bi bi-database-fill'),
		   ('Redes', 'Tecnologia da Informação e Ciência da Computação','bi bi-wifi'),
		   ('Hardware', 'Tecnologia da Informação e Ciência da Computação','bi bi-cpu-fill'),
		   ('Segurança da Informação', 'Tecnologia da Informação e Ciência da Computação','bi bi-shield-lock-fill'),
		   ('Gestão de TI', 'Tecnologia da Informação e Ciência da Computação','bi bi-pc-display'),
		   ('Matemática Aplicada à Computação', 'Tecnologia da Informação e Ciência da Computação','bi bi-laptop-fill'),

		   ('Empreendedorismo', 'Negócios e Finanças','bi bi-buildings-fill'),
		   ('Marketing Digital', 'Negócios e Finanças','bi bi-globe-americas'),
		   ('Contabilidade', 'Negócios e Finanças','bi bi-bar-chart-fill'),
		   ('Gestão de Negócios', 'Negócios e Finanças','bi bi-briefcase-fill'),
		   ('Economia Doméstica', 'Negócios e Finanças','bi bi-currency-dollar'),
		   ('Finanças Pessoais', 'Negócios e Finanças','bi bi-currency-euro'),
		   ('Investimentos', 'Negócios e Finanças','bi bi-currency-bitcoin'),
		   ('Mercado Financeiro', 'Negócios e Finanças','bi bi-bank'),
		   ('Marketing', 'Negócios e Finanças','bi bi-megaphone-fill'),
		   ('Recursos Humanos', 'Negócios e Finanças','bi bi-people-fill'),
		   ('Matemática Financeira', 'Negócios e Finanças','bi bi-percent'),

		   ('História', 'Humanidades e Metafísica','bi bi-hourglass-split'),
		   ('Geografia', 'Humanidades e Metafísica','bi bi-globe-europe-africa'),
		   ('Filosofia', 'Humanidades e Metafísica','bi bi-chat-right-quote-fill'),
		   ('Economia', 'Humanidades e Metafísica','bi bi-cash'),
		   ('Microeconomia', 'Humanidades e Metafísica','bi bi-wallet'),
		   ('Macroeconomia', 'Humanidades e Metafísica','bi bi-globe'),
		   ('Teologia', 'Humanidades e Metafísica','bi bi-person-arms-up'),
		   ('Religião', 'Humanidades e Metafísica','bi bi-yin-yang'),
		   ('Psicologia', 'Humanidades e Metafísica','bi bi-lightbulb-fill'),
		   ('Sociologia', 'Humanidades e Metafísica','bi bi-people-fill'),
		   ('Antropologia', 'Humanidades e Metafísica','bi bi-people-fill'),
		   ('Linguística', 'Humanidades e Metafísica','bi bi-translate'),
		   ('Direito', 'Humanidades e Metafísica','bi bi-briefcase-fill'),
		   ('Ciências Políticas', 'Humanidades e Metafísica','bi bi-briefcase-fill'),

		   ('Design Gráfico', 'Humanidades e Metafísica','bi bi-pencil-fill'),
		   ('UI/UX', 'Humanidades e Metafísica','bi bi-window-fullscreen'),
		   ('Fotografia', 'Humanidades e Metafísica','bi bi-camera-fill'),
		   ('Edição de Vídeos', 'Humanidades e Metafísica','bi bi-camera-video-fill'),
		   ('Ilustrações Digitais', 'Humanidades e Metafísica','bi bi-card-image'),

		   ('Matemática', 'Ciências Exatas e da Natureza','bi bi-123'),
		   ('Química', 'Ciências Exatas e da Natureza','bi bi-lightning-charge-fill'),
		   ('Física', 'Ciências Exatas e da Natureza','bi bi-radioactive'),
		   ('Biologia', 'Ciências Exatas e da Natureza','bi bi-flower1'),
		   ('Estatística', 'Ciências Exatas e da Natureza','bi bi-calculator'),

		   ('Neurociência', 'Medicina','bi bi-lightbulb-fill'),
		   ('Veterinária', 'Medicina','bi bi-hospital-fill'),
		   ('Biologia Humana', 'Medicina','bi bi-lungs-fill'),
		   ('Medicina Alternativa', 'Medicina','bi bi-capsule'),

		   ('Língua Portuguesa', 'Idiomas','bi bi-translate'),
		   ('Língua Inglesa', 'Idiomas','bi bi-translate'),
		   ('Língua Francesa', 'Idiomas','bi bi-translate'),
		   ('Língua Alemã', 'Idiomas','bi bi-translate'),
		   ('Língua Italiana', 'Idiomas','bi bi-translate'),
		   ('Língua Espanhola', 'Idiomas','bi bi-translate'),
		   ('Língua Holandesa', 'Idiomas','bi bi-translate'),
		   ('Língua Russa', 'Idiomas','bi bi-translate'),
		   ('Língua Norueguesa', 'Idiomas','bi bi-translate'),
		   ('Mandarim', 'Idiomas','bi bi-translate'),
		   ('Cantonês', 'Idiomas','bi bi-translate'),
		   ('Língua Japonesa', 'Idiomas','bi bi-translate'),
		   ('Hindi', 'Idiomas','bi bi-translate'),
		   ('Língua Árabe', 'Idiomas','bi bi-translate'),
		   ('Língua Sueca', 'Idiomas','bi bi-translate'),
		   ('Língua Dinamarquesa', 'Idiomas','bi bi-translate'),
		   ('Língua Finlandesa', 'Idiomas','bi bi-translate'),
		   ('Língua Húngara', 'Idiomas','bi bi-translate'),
		   ('Língua Letã', 'Idiomas','bi bi-translate'),
		   ('Língua Swali', 'Idiomas','bi bi-translate'),
		   ('Língua Esperanto', 'Idiomas','bi bi-translate'),
		   ('Língua Latina', 'Idiomas','bi bi-translate'),
		   ('Língua Grega', 'Idiomas','bi bi-translate'),
		   ('Língua Polonesa', 'Idiomas','bi bi-translate'),
		   ('Língua Serbo-Croata', 'Idiomas','bi bi-translate'),
		   ('Língua Romena', 'Idiomas','bi bi-translate'),
		   ('Língua Catalã', 'Idiomas','bi bi-translate'),
		   ('Língua Ucraniana', 'Idiomas','bi bi-translate'),
		   ('Língua Estoniana', 'Idiomas','bi bi-translate'),
		   ('Língua Búlgara', 'Idiomas','bi bi-translate'),
		   ('Língua Turca', 'Idiomas','bi bi-translate'),
		   ('Língua Persa', 'Idiomas','bi bi-translate'),
		   ('Língua Vietnamita', 'Idiomas','bi bi-translate'),
		   ('Língua Irlandesa', 'Idiomas','bi bi-translate'),
		   ('Língua Hebraíca', 'Idiomas','bi bi-translate'),
		   ('Língua Indonésia', 'Idiomas','bi bi-translate'),
		   ('Língua Tcheca', 'Idiomas','bi bi-translate'),
		   ('Língua Havaiana', 'Idiomas','bi bi-translate'),
		   ('Língua Zulu', 'Idiomas','bi bi-translate'),
		   ('Língua Galesa', 'Idiomas','bi bi-translate'),
		   ('Língua Gaélica-Escocesa', 'Idiomas','bi bi-translate'),
		   ('Língua Créole', 'Idiomas','bi bi-translate'),
		   ('Língua Coreana', 'Idiomas','bi bi-translate'),
		   ('Língua Bengali', 'Idiomas','bi bi-translate'),
		   ('Língua Protogramânica', 'Idiomas','bi bi-translate'),
		   ('Língua Armena', 'Idiomas','bi bi-translate'),

		   ('Comunicação', 'Desenvolvimento Pessoal e Saúde','bi bi-chat'),
		   ('Liderança', 'Desenvolvimento Pessoal e Saúde','bi bi-people-fill'),
		   ('Autoconhecimento', 'Desenvolvimento Pessoal e Saúde','bi bi-lightbulb-fill'),
		   ('Gestão do Tempo', 'Desenvolvimento Pessoal e Saúde','bi bi-stopwatch-fill'),
		   ('Saúde Mental e Emocional', 'Desenvolvimento Pessoal e Saúde','bi bi-lightbulb-fill'),
		   ('Nutrição', 'Desenvolvimento Pessoal e Saúde','bi bi-egg-fried'),
		   ('Yoga', 'Desenvolvimento Pessoal e Saúde','bi bi-yin-yang'),

		   ('Xadrez', 'Esportes','bi bi-controller'),
		   ('Musculação e Calistenia', 'Esportes','bi bi-controller'),
		   ('Futebol', 'Esportes','bi bi-controller'),
		   ('Basquete', 'Esportes','bi bi-controller'),
		   ('Vôlei', 'Esportes','bi bi-controller'),
		   ('e-Sports', 'Esportes','bi bi-controller'),

		   ('Canto', 'Música','bi bi-music-note-beamed'),
		   ('Guitarra', 'Música','bi bi-music-note-beamed'),
		   ('Bateria', 'Música','bi bi-music-note-beamed'),
		   ('Baixo', 'Música','bi bi-music-note-beamed'),
		   ('Violino', 'Música','bi bi-music-note-beamed'),
		   ('Violoncelo', 'Música','bi bi-music-note-beamed'),
		   ('Saxofone', 'Música','bi bi-music-note-beamed'),
		   ('Piano e Cravo', 'Música','bi bi-music-note-beamed'),
		   ('Instrumentos de Sopro', 'Música','bi bi-music-note-beamed'),
		   ('Teclado', 'Música','bi bi-music-note-beamed'),
		   ('Sintetizadores', 'Música','bi bi-music-note-beamed'),
		   ('DJ', 'Música','bi bi-vinyl-fill'),
		   ('Produção Musical', 'Música','bi bi-vinyl-fill'),

		   ('Desenho', 'Artes', 'bi bi-pencil-fill'),
		   ('Escrita Criativa', 'Artes','bi bi-pen-fill'),
		   ('Teatro', 'Artes','bi bi-palette-fill'),
		   ('Cinema', 'Artes','bi bi-film'),
		   ('Dança', 'Artes','bi bi-palette-fill'),
		   ('Culinária', 'Artes','bi bi-egg-fried'),
		   ('Jardinagem', 'Artes','bi bi-flower1'),
		   ('Moda', 'Artes','bi bi-palette-fill'),

		   ('Metodologias de Ensino', 'Educação','bi bi-easel-fill'),
		   ('Pedagogia', 'Educação','bi bi-easel2-fill'),
		   ('Técnicas para o Aprendizado', 'Educação','bi bi-palette-fill'),
		   ('Educação Infantil', 'Educação','bi bi-easel3-fill'),
		   ('Educação de Adultos', 'Educação','bi bi-mortarboard-fill'),
		   ('Tecnologias Educacionais', 'Educação','bi bi-motherboard-fill'),

		   ('Viagens', 'Educação','bi bi-backpack-fill'),
		   ('Faça Você Mesmo', 'Educação','bi bi-hammer'),
		   ('Carpintaria', 'Educação','bi bi-hammer'),
		   ('Metalurgia', 'Educação','bi bi-gear-fill'),
		   ('Mecânica', 'Educação','bi bi-car-front-fill')
GO


